#!/bin/bash
# manage the nginx server

# for MacOS with nginx installed with Homebrew, the configuration file
# is located at /usr/local/etc/nginx/nginx.conf.

usage() 
{
	echo 'USAGE:'
	echo 'run_nginx [ quit | stop | reload | reopen ]'
	echo
	echo 'run_nginx (with no parameters) starts the server'
	echo
	echo 'run_nginx quit      graceful shutdown'
	echo 'run_nginx stop      fast shutdown'
	echo 'run_nginx reload    reload the configuration file'
	echo 'run_nginx reopen    reopen the log files'
}

if [ $# -gt 1 ]
then
	usage
	exit 1
elif [ $# -eq 1 ]
then
	parm=$1
fi

if [ "X$parm" != "X" ]
then
    nginx -s $parm
else
    nginx
fi

# EOF

