# Generated by Django 2.1.7 on 2019-03-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('Activity_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Activity ID')),
                ('BoxNumber', models.CharField(max_length=8, unique=True, verbose_name='Visible Box Number')),
                ('BoxTypeCode', models.CharField(max_length=10, verbose_name='Box Type Code')),
                ('LocRow', models.CharField(max_length=2, verbose_name='Row Location')),
                ('LocBin', models.CharField(max_length=2, verbose_name='Bin Location')),
                ('LocTier', models.CharField(max_length=2, verbose_name='Tier Location')),
                ('ProdName', models.CharField(max_length=30, verbose_name='Product Name')),
                ('ProdCatName', models.CharField(max_length=30, verbose_name='Product Category Name')),
                ('DateFilled', models.DateField(verbose_name='Date Box Filled')),
                ('DateConsumed', models.DateField(verbose_name='Date Box Emptied')),
                ('ExpirationYear', models.IntegerField(verbose_name='Year Expired')),
                ('ExpirationMonthStart', models.IntegerField(null=True, verbose_name='Start Expiration Month')),
                ('ExpirationMonthEnd', models.IntegerField(null=True, verbose_name='End Expiration Month')),
                ('Quantity', models.IntegerField(null=True, verbose_name='Quantity in Box')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('BoxID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Box ID')),
                ('BoxNumber', models.CharField(max_length=8, unique=True, verbose_name='Visible Box Number')),
                ('LocRow', models.CharField(max_length=2, null=True, verbose_name='Row Location')),
                ('LocBin', models.CharField(max_length=2, null=True, verbose_name='Bin Location')),
                ('LocTier', models.CharField(max_length=2, null=True, verbose_name='Tier Location')),
                ('ExpirationYear', models.IntegerField(null=True, verbose_name='Year Product Expires')),
                ('ExpirationMonthStart', models.IntegerField(null=True, verbose_name='Expiration Start Month (Optional)')),
                ('ExpirationMonthEnd', models.IntegerField(null=True, verbose_name='Expiration End Month (Optional)')),
                ('DateFilled', models.DateTimeField(null=True, verbose_name='Date Box Filled')),
                ('Quantity', models.IntegerField(null=True, verbose_name='Quantity in Box')),
            ],
        ),
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('BoxTypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Box Type ID')),
                ('BoxTypeCode', models.CharField(max_length=10, unique=True, verbose_name='Box Type Code')),
                ('BoxTypeDescr', models.CharField(max_length=30, verbose_name='Box Type Description')),
                ('BoxTypeQty', models.IntegerField(verbose_name='Default Box Type Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('ConstraintID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Constraint ID')),
                ('ConstraintName', models.CharField(max_length=30, verbose_name='Constraint Name')),
                ('ConstraintType', models.CharField(choices=[('Int-MM', 'Integer Min/Max'), ('Char-MM', 'Character Min/Max'), ('Int-List', 'Integer Valid List'), ('Char-List', 'Character Valid List')], max_length=15, verbose_name='Constraint Type')),
                ('ConstraintMin', models.CharField(max_length=30, null=True, verbose_name='Minimum Valid Constraint')),
                ('ConstraintMax', models.CharField(max_length=30, null=True, verbose_name='Maximum Valid Constraint')),
                ('ConstraintList', models.CharField(max_length=500, null=True, verbose_name='Valid Constraint List')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProdID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Product ID')),
                ('ProdName', models.CharField(max_length=30, verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('ProdCatID', models.AutoField(primary_key=True, serialize=False, verbose_name='Internal Product Category ID')),
                ('ProdCatName', models.CharField(max_length=30, unique=True, verbose_name='Product Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ProdCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fpiweb.ProductCategory', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='box',
            name='BoxType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fpiweb.BoxType', verbose_name='Type of Box'),
        ),
        migrations.AddField(
            model_name='box',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Product', verbose_name='Product'),
        ),
    ]
