# Generated by Django 2.1.7 on 2019-03-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Duration',
            field=models.IntegerField(default=9, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='ExpirationMonthEnd',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Expiration Month'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ExpirationMonthStart',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Expiration Month'),
        ),
        migrations.AlterField(
            model_name='box',
            name='DateFilled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Box Filled'),
        ),
        migrations.AlterField(
            model_name='box',
            name='ExpirationMonthEnd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expiration End Month (Optional)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='ExpirationMonthStart',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expiration Start Month (Optional)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='ExpirationYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Product Expires'),
        ),
        migrations.AlterField(
            model_name='box',
            name='LocBin',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bin Location'),
        ),
        migrations.AlterField(
            model_name='box',
            name='LocRow',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Row Location'),
        ),
        migrations.AlterField(
            model_name='box',
            name='LocTier',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tier Location'),
        ),
        migrations.AlterField(
            model_name='box',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='box',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity in Box'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='ConstraintList',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Valid Constraint List'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='ConstraintMax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Maximum Valid Constraint'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='ConstraintMin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Minimum Valid Constraint'),
        ),
    ]
