# Generated by Django 2.1.7 on 2019-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0003_constraints_constraintdescr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['DateConsumed', ['BoxNumber']]},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['BoxNumber']},
        ),
        migrations.AlterModelOptions(
            name='boxtype',
            options={'ordering': ['BoxTypeCode']},
        ),
        migrations.AlterModelOptions(
            name='constraints',
            options={'ordering': ['ConstraintName']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['ProdName']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['ProdCatName']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='ProdCatDescr',
            field=models.TextField(null=True, verbose_name='Product Category Description'),
        ),
    ]
