# Generated by Django 2.1.7 on 2019-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0005_auto_20190403_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Constraints',
            old_name='constraint_id',
            new_name='id',
        )
    ]
