# Generated by Django 2.1.7 on 2019-04-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0007_auto_20190406_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Activity',
            old_name='activity_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='Box',
            old_name='box_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='BoxType',
            old_name='box_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='Product',
            old_name='prod_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ProductCategory',
            old_name='prod_cat_id',
            new_name='id',
        ),
    ]
