# Generated by Django 2.1.7 on 2019-04-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0009_auto_20190410_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExample',
            fields=[
                ('id', models.AutoField(help_text='Internal reccord identifier for product example', primary_key=True, serialize=False, verbose_name='Internal Product Example ID')),
                ('prod_example_name', models.CharField(help_text='Name of example product.', max_length=30, unique=True, verbose_name='Product Example Name')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='box_number',
            field=models.CharField(help_text='Box number on box at time of consumption.', max_length=8, verbose_name='Visible Box Number'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='constraint_name',
            field=models.CharField(help_text='Coded name of a constraint.', max_length=30, unique=True, verbose_name='Constraint Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(help_text='Name of this product.', max_length=30, unique=True, verbose_name='product Name'),
        ),
        migrations.AddField(
            model_name='productexample',
            name='prod_id',
            field=models.ForeignKey(help_text='Product with which this product name is associated.', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Product', verbose_name='Product'),
        ),
    ]
