# Generated by Django 2.1.7 on 2019-04-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0010_auto_20190415_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productexample',
            options={'ordering': ['prod_example_name']},
        ),
    ]
