# Generated by Django 2.2 on 2019-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0013_auto_20190420_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_consumed', 'box_number'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['box_number'], 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='constraints',
            options={'ordering': ['constraint_name'], 'verbose_name_plural': 'Constraints'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['prod_cat_name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='exp_month_start',
            field=models.IntegerField(blank=True, help_text='Optional starting month product would have expired.', null=True, verbose_name='Start Expiration Month'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc_row',
            field=models.CharField(help_text='Row box was in at the time product was consumed.', max_length=2, verbose_name='Row Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Approximate number of items in the box when it was filled.', verbose_name='Quantity in Box'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='constraint_descr',
            field=models.TextField(help_text='Description of this constraint.', null=True, verbose_name='Constraint Description'),
        ),
    ]
