# Generated by Django 2.2.1 on 2019-06-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0015_box_print_box_number_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='print_box_number_label',
        ),
    ]
