# Generated by Django 2.2.2 on 2019-06-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpiweb', '0016_remove_box_print_box_number_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocBin',
            fields=[
                ('id', models.AutoField(help_text='Internal record id for location bin.', primary_key=True, serialize=False, verbose_name='Internal Location Bin ID')),
                ('loc_bin', models.CharField(help_text='Location bin designation', max_length=2, unique=True, verbose_name='Loc Bin')),
                ('loc_bin_descr', models.CharField(help_text='Locationn bin description', max_length=20, verbose_name='Loc Description')),
            ],
            options={
                'verbose_name_plural': 'Loc Bins',
                'ordering': ['loc_bin'],
            },
        ),
        migrations.CreateModel(
            name='LocRow',
            fields=[
                ('id', models.AutoField(help_text='Internal record id for location row.', primary_key=True, serialize=False, verbose_name='Internal Location Row ID')),
                ('loc_row', models.CharField(help_text='Location row designation', max_length=2, unique=True, verbose_name='Loc Row')),
                ('loc_row_descr', models.CharField(help_text='Locationn row description', max_length=20, verbose_name='Loc Description')),
            ],
            options={
                'verbose_name_plural': 'Loc Rows',
                'ordering': ['loc_row'],
            },
        ),
        migrations.CreateModel(
            name='LocTier',
            fields=[
                ('id', models.AutoField(help_text='Internal record id for location tier.', primary_key=True, serialize=False, verbose_name='Internal Location Tier ID')),
                ('loc_tier', models.CharField(help_text='Location tier designation', max_length=2, unique=True, verbose_name='Loc Tier')),
                ('loc_tier_descr', models.CharField(help_text='Locationn tier description', max_length=20, verbose_name='Loc Tier Description')),
            ],
            options={
                'verbose_name_plural': 'Loc Tiers',
                'ordering': ['loc_tier'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=30, null=True, verbose_name='Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(help_text='Internal record identifier for location.', primary_key=True, serialize=False, verbose_name='Internal Location ID')),
                ('loc_code', models.CharField(help_text='Location code', max_length=12, unique=True, verbose_name='Location Code')),
                ('loc_descr', models.CharField(help_text='Location description', max_length=25, verbose_name='Location Description')),
                ('loc_in_warehouse', models.BooleanField(default=True, help_text='In warehouse?', verbose_name='In warehouse?')),
                ('loc_bin', models.ForeignKey(help_text='Loc bin', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocBin', verbose_name='Bin')),
                ('loc_row', models.ForeignKey(help_text='Loc row', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocRow', verbose_name='Row')),
                ('loc_tier', models.ForeignKey(help_text='Loc tier', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocTier', verbose_name='Tier')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['loc_code'],
            },
        ),
    ]
