# Generated by Django 2.2.4 on 2019-08-19 02:11

from django.db import migrations, models
import fpiweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0018_profile_active_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productexample',
            options={'ordering': ['prod_example_name'], 'verbose_name_plural': 'Product Examples'},
        ),
        migrations.AddField(
            model_name='activity',
            name='adjustment',
            field=models.CharField(choices=[(fpiweb.models.ActivityAdjustmentType(''), 'Normal'), (fpiweb.models.ActivityAdjustmentType('Auto Emptied'), 'Automatically Emptied Box'), (fpiweb.models.ActivityAdjustmentType('Auto Filled'), 'Automatically Filled Box')], default=fpiweb.models.adjustment_type_default, help_text='If this is an adjustment entry, what type?', max_length=50, verbose_name='Adjustment?'),
        ),
        migrations.AlterField(
            model_name='locbin',
            name='loc_bin_descr',
            field=models.CharField(help_text='Location bin description', max_length=20, verbose_name='Loc Description'),
        ),
        migrations.AlterField(
            model_name='locrow',
            name='loc_row_descr',
            field=models.CharField(help_text='Location row description', max_length=20, verbose_name='Loc Description'),
        ),
        migrations.AlterField(
            model_name='loctier',
            name='loc_tier_descr',
            field=models.CharField(help_text='Location tier description', max_length=20, verbose_name='Loc Tier Description'),
        ),
    ]
