# Generated by Django 2.2.4 on 2019-08-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpiweb', '0018_profile_active_location'),
    ]
    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(help_text='Internal record identifier for a pallet.', primary_key=True, serialize=False, verbose_name='Internal Pallet ID')),
                ('pallet_status', models.CharField(choices=[('Fill', 'Fill pallet for new location'), ('Merge', 'Merging boxes on pallet'), ('Move', 'Moving boxes to new location')], help_text='Current status of pallet.', max_length=15, verbose_name='Pallet Status')),
            ],
            options={
                'verbose_name_plural': 'Pallets',
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productexample',
            options={'ordering': ['prod_example_name'], 'verbose_name_plural': 'Product Examples'},
        ),
        migrations.AddField(
            model_name='activity',
            name='adjustment_code',
            field=models.CharField(blank=True, choices=[('Add Emptied', 'Add emptied previous contents'), ('Move Added', 'Move added box'), ('Move Emptied', 'Move emptied prevous contents'), ('Consume Added', 'Consume added box')], help_text='Coded reason if this entry was adjusted', max_length=15, null=True, verbose_name='Adjustment Code'),
        ),
        migrations.AlterField(
            model_name='locbin',
            name='loc_bin_descr',
            field=models.CharField(help_text='Location bin description', max_length=20, verbose_name='Loc Bin Description'),
        ),
        migrations.AlterField(
            model_name='locrow',
            name='loc_row_descr',
            field=models.CharField(help_text='Location row description', max_length=20, verbose_name='Loc Row Description'),
        ),
        migrations.AlterField(
            model_name='loctier',
            name='loc_tier_descr',
            field=models.CharField(help_text='Location tier description', max_length=20, verbose_name='Loc Tier Description'),
        ),
        migrations.CreateModel(
            name='PalletBox',
            fields=[
                ('id', models.AutoField(help_text='Internal record identifier for a pallet box.', primary_key=True, serialize=False, verbose_name='Internal Pallet Box ID')),
                ('box_status', models.CharField(choices=[('New', 'New box added'), ('Original', 'Box already here'), ('Move', 'Box being moved')], help_text='Box on pallet status.', max_length=15, verbose_name='Box Status')),
                ('box_id', models.ForeignKey(help_text='Internal record ideentifier for a box.', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Box')),
                ('pallet_id', models.ForeignKey(help_text='Internal record identifier for a pallet.', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Pallet')),
            ],
            options={
                'verbose_name_plural': 'Pallet Boxes',
                'ordering': '',
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='pallet_loc_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocBin'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='pallet_loc_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocRow'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='pallet_loc_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fpiweb.LocTier'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
