# Generated by Django 2.2.3 on 2019-10-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0019_pallet_tables_and_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_consumed',
            field=models.DateTimeField(blank=True, help_text='Date product was consumed.', null=True, verbose_name='Date Box Emptied'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_filled',
            field=models.DateTimeField(help_text='Approximate date product was put in the box.', verbose_name='Date Box Filled'),
        ),
        migrations.AlterField(
            model_name='palletbox',
            name='box',
            field=models.ForeignKey(help_text='Internal record ideentifier for a box.', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Box'),
        ),
    ]
