# Generated by Django 2.2.4 on 2019-08-05 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0019_add_pallet_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletbox',
            name='box_number',
            field=models.CharField(default='BOX99999', help_text='Number printed in the label on the box.', max_length=8, unique=True, verbose_name='Visible Box Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palletbox',
            name='exp_month_end',
            field=models.IntegerField(blank=True, help_text='Optional ending month range of when the product expires, if filled.', null=True, verbose_name='Expiration End Month (Optional)'),
        ),
        migrations.AddField(
            model_name='palletbox',
            name='exp_month_start',
            field=models.IntegerField(blank=True, help_text='Optional starting month range of when the product expires, if filled.', null=True, verbose_name='Expiration Start Month (Optional)'),
        ),
        migrations.AddField(
            model_name='palletbox',
            name='exp_year',
            field=models.IntegerField(default=9999, help_text='Year the product expires, if filled.', verbose_name='Year Product Expires'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palletbox',
            name='product',
            field=models.ForeignKey(default=1, help_text='Product contained in this box, if filled.', on_delete=django.db.models.deletion.PROTECT, to='fpiweb.Product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
