# Generated by Django 2.2.4 on 2019-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0019_ActivityAdjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='adjustment_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Adjustment Code'),
        ),
    ]
