# Generated by Django 2.2.5 on 2019-09-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0020_add_more_fields_to_pallet_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_consumed',
            field=models.DateField(blank=True, help_text='Date product was consumed.', null=True, verbose_name='Date Box Emptied'),
        ),
    ]
