# Generated by Django 2.2.6 on 2019-10-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0020_auto_20191023_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='loc_bin',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='loc_row',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='loc_tier',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of Box', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpiweb.Location'),
        ),
    ]
