# Generated by Django 2.2.6 on 2019-11-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0021_auto_20191022_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='loc_bin',
        ),
        migrations.RemoveField(
            model_name='box',
            name='loc_row',
        ),
        migrations.RemoveField(
            model_name='box',
            name='loc_tier',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='pallet_loc_bin',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='pallet_loc_row',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='pallet_loc_tier',
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of Box', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpiweb.Location'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Pallet Location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpiweb.Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_consumed',
            field=models.DateField(blank=True, help_text='Date product was consumed.', null=True, verbose_name='Date Box Emptied'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_filled',
            field=models.DateField(help_text='Approximate date product was put in the box.', verbose_name='Date Box Filled'),
        ),
    ]
