# Generated by Django 2.2.9 on 2020-01-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0023_auto_20200102_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallet',
            options={'ordering': ('name',), 'verbose_name_plural': 'Pallets'},
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='palletbox',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='active_location',
        ),
        migrations.AddField(
            model_name='pallet',
            name='name',
            field=models.CharField(default='(name)', help_text='Name of pallet', max_length=200, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='active_pallet',
            field=models.ForeignKey(blank=True, help_text='Active Pallet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpiweb.Pallet'),
        ),
    ]
