# Generated by Django 2.2.9 on 2020-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0024_change_pallet_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletbox',
            name='box_number',
            field=models.CharField(default='BOX99999', help_text='Box number for this pallet box.', max_length=8, unique=True, verbose_name='Box number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='adjustment_code',
            field=models.CharField(blank=True, choices=[('Fill Emptied', 'Fill emptied previous contents'), ('Move Added', 'Move added box'), ('Consume Added', 'Consume added box'), ('Consume Emptied', 'Consume emptied previous contents')], help_text='Coded reason if this entry was adjusted', max_length=15, null=True, verbose_name='Adjustment Code'),
        ),
    ]
