# Generated by Django 3.0.7 on 2020-06-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0028_add_activity_adj_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['box_number'], 'permissions': [('check_in_box', 'Check In Box'), ('check_out_box', 'Check Out (Consume) Box'), ('move_box', 'Move Box'), ('print_labels_box', 'Print Labels')], 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='pallet',
            options={'ordering': ('name',), 'permissions': [('build_pallet', 'Build pallet'), ('move_pallet', 'Move pallet')], 'verbose_name_plural': 'Pallets'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('dummy_profile', 'Dummy permission (do not grant to anyone!)'), ('view_system_maintenance', 'View System Maintenance')]},
        ),
    ]
