name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql db: "WARM"
        postgresql user: "admin"
        postgresql password: "admin"
    - name: Create private directory
      run: |
        mkdir FPIDjango/private
    - name: Create settings_private.py
      run: |
        echo "DB_ENGINE = 'django.db.backends.postgresql'" > FPIDjango/private/settings_private.py
        echo "DB_NAME = 'WARM'" >> FPIDjango/private/settings_private.py
        echo "DB_USER = 'admin'" >> FPIDjango/private/settings_private.py
        echo "DB_PSWD = 'admin'" >> FPIDjango/private/settings_private.py
        echo "DB_HOST = 'localhost'" >> FPIDjango/private/settings_private.py
        echo "DB_PORT = '8080'" >> FPIDjango/private/settings_private.py
        echo "MY_SECRET_KEY = '<specify your own random  string of 50 characters>'" >> FPIDjango/private/settings_private.py
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
