name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql db: "WARM"
        postgresql user: "admin"
        postgresql password: "admin"
    - name: Create private directory
      run: |
        mkdir FPIDjango/private
    - uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "FPIDjango/private/settings_private.py"
        FILE_DATA: |
          DB_ENGINE = "django.db.backends.postgresql"
          DB_NAME = "WARM"
          DB_USER = "admin"
          DB_PSWD = "admin"
          DB_HOST = "localhost"
          DB_PORT = "8080"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
